global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ecs_services'
    metrics_path: /metrics
    static_configs:
      - targets: ['microservice1:80', 'microservice2:8080']


  - job_name: 'jenkins'
    static_configs:
      - targets: ['localhost:8080']

